source 'https://rubygems.org'
ruby '2.3.4'

gem 'aws-sdk'
gem 'config', '1.4.0'
gem 'coveralls', require: false
gem 'dotenv-rails'
gem 'ftpd', '~> 2.1'
gem 'fakes3'
gem 'pry'
gem 'rake', '~> 11.2', '>= 11.2.2'
gem 'rubocop'
gem 'test-unit'
gem 'eventmachine', '~> 1.2', '>= 1.2.3'
gem 'slack-ruby-client'
gem 'faye-websocket'