ftp:
  host: 127.0.0.1
  username: test
  password: test
  port: 10102
aws:
  s3:
    bucket_name: test_bucket
    secret_access_key: xxxx
    access_key_id: yyyy
    region: ap-north-east
    endpoint: http://localhost:4567
maper:
  - map.csv